// Tinyhouse Atelier — data
// Every photo and PDF page from the studio set is wired in. Specs derive from
// the wall-section study (140 mm LGSF / 130 mm Rockwool / 12 mm Guardex /
// metal-tile roof) shown in our atelier photo book.

const M = 'public/media/photos/';
const SR = 'public/media/serenity/';
const AF = 'public/media/aframe/';
const CA = 'public/media/callisto/';
const i = (n) => M + 'img-' + String(n).padStart(3, '0') + '.jpg';
const sr = (n) => SR + 'page-' + String(n).padStart(2, '0') + '.jpg';
const af = (n) => AF + 'page-' + String(n).padStart(2, '0') + '.jpg';
const ca = (n) => CA + 'page-' + String(n).padStart(2, '0') + '.jpg';

window.DATA = {
  tinyHouses: [
    {
      id: 'th-serenity',
      name: 'Serenity',
      sub: 'Modern gable · loft sleeping · 4 berth',
      length: '7.5 m',
      width: '2.55 m',
      height: '4.10 m',
      sleeps: '4',
      area: '38 m²',
      weight: '4,800 kg',
      priceGBP: 58500,
      priceEUR: 68400,
      frame: '140 mm LGSF · galvanised',
      insulation: '130 mm Rockwool walls · 80 mm floor',
      cladding: 'Standing-seam steel · vertical',
      roof: 'Metal tile on 11 mm OSB',
      hero: sr(2),
      images: [sr(2), sr(7), sr(6), sr(1), sr(8), sr(10), sr(9), sr(4), sr(5), sr(3), i(26), i(78)],
      thumbCaptions: [
        '¾ Exterior · stand', 'Living · gable', 'Loft view',
        'Stair · LED inset', 'Galley · island', 'Stair · storage',
        'Bathroom · shower', 'Bathroom · vanity', 'Bath · alt view',
        'Pantry · accent', 'Night render', 'On location',
      ],
      pdf: 'public/media/serenity-model.pdf',
      pdfLabel: 'Serenity floor plan & spec book — PDF',
      story: 'A two-storey gable with the loft above the bathroom. The same wall build-up as our larger lodges — 140 mm light-gauge steel frame, 130 mm Rockwool, Guardex twice, then aluminium-foil membrane and decorative plaster — but compressed into a 7.5 m footprint that fits any plot.',
    },
    {
      id: 'th-aurora',
      name: 'Aurora A-Frame',
      sub: 'A-frame · towable · two berth',
      length: '6.8 m',
      width: '2.50 m',
      height: '4.20 m (peak)',
      sleeps: '2',
      area: '22 m²',
      weight: '3,400 kg',
      priceGBP: 28900,
      priceEUR: 33800,
      frame: '140 mm LGSF on tandem-axle chassis',
      insulation: '130 mm Rockwool · vapour-controlled',
      cladding: 'Larch · horizontal · matt black trim',
      roof: 'Standing-seam steel · 0.7 mm',
      hero: af(1),
      images: [af(1), af(3), af(4), af(9), af(7), af(12), af(10), af(2), af(5), af(6), af(8), af(11)],
      thumbCaptions: [
        'A-frame · ¾', 'Cladding side', 'Kitchen · island',
        'Galley · sink', 'Living · pentagon window', 'Loft sleeping',
        'Bathroom', 'Roof line · LED', 'Long view',
        'Galley + window', 'Wide hall', 'Loft railing',
      ],
      pdf: 'public/media/aurora-aframe.pdf',
      pdfLabel: 'Aurora A-Frame photo book — PDF',
      story: 'Towable on a 750 kg-rated tandem chassis. The A-frame profile sheds snow and rain in any climate; inside, the slope wraps a galley kitchen and a sleeping loft over a full shower room. Built for one couple and a long winter.',
    },
    {
      id: 'th-voyager',
      name: 'Voyager',
      sub: 'Modern lodge · trailer-mounted · 3 berth',
      length: '9.6 m',
      width: '2.55 m',
      height: '3.80 m',
      sleeps: '3',
      area: '28 m²',
      weight: '5,200 kg',
      priceGBP: 44900,
      priceEUR: 52400,
      frame: '140 mm LGSF · welded chassis',
      insulation: '130 mm Rockwool · 100 mm roof',
      cladding: 'Wood-look composite + Corten panels',
      roof: 'Standing-seam steel · charcoal',
      hero: i(41),
      images: [
        i(41), i(42), i(63), i(64), i(65), i(40), i(39),
        i(38), i(27), i(28), i(29), i(30), i(31),
        i(43), i(44), i(45), i(46), i(48), i(52),
        i(35), i(49), i(67), i(68), i(69),
        i(74), i(76), i(77), i(80), i(81),
      ],
      thumbCaptions: [
        '¾ Exterior · field', 'Side elevation', 'Aerial · pair', 'Hitch detail',
        'On plot', 'Approach', 'Field view',
        'Galley · loft above', 'Galley · induction', 'Kitchen · spice nook',
        'Stairs · light', 'Stair detail', 'Worktop · island',
        'Hallway', 'Stair · loft', 'Loft view', 'Hallway light', 'Hall · window', 'Throughway',
        'Bath · industrial glass', 'Bath · marble', 'Living · grey sectional', 'Stair detail', 'Open plan',
        'Living · TV', 'Bedroom', 'Bedroom · long', 'Hall · entrance', 'Hall · bedroom side',
      ],
      story: 'Our flagship trailer-mounted lodge. 9.6 m on the road, ready for occupation in twenty minutes once the levelling jacks are down. Composite wood-look siding takes UK and continental weather without re-staining; the roof is standing-seam steel that will outlive the warranty by decades.',
    },
    {
      id: 'th-vortex',
      name: 'Vortex Compact',
      sub: 'Single occupant · towable · garden cabin',
      length: '5.2 m',
      width: '2.40 m',
      height: '3.20 m',
      sleeps: '1–2',
      area: '12 m²',
      weight: '2,200 kg',
      priceGBP: 24500,
      priceEUR: 28600,
      frame: '90 mm LGSF · galvanised',
      insulation: '100 mm Rockwool',
      cladding: 'Cedar T&G · clear oil',
      roof: 'Metal tile · charcoal',
      hero: i(100),
      images: [
        i(100), i(104), i(53), i(54), i(102), i(103),
        i(14), i(15), i(16), i(17), i(18), i(19), i(20),
        i(21), i(22), i(23), i(24), i(25),
        i(32), i(33), i(34), i(36), i(47), i(50),
        i(51), i(55), i(56), i(57), i(58), i(59), i(60), i(61), i(62),
        i(66), i(70), i(71), i(72), i(73),
      ],
      thumbCaptions: [
        '¾ Exterior · workshop', 'Pair · Kurtsan yard', 'Cladding detail',
        'On location', 'Pentagon front', 'Through doors',
        'Bath · compact', 'Hall · long', 'Bedroom · loft', 'Galley · view', 'Loft · double',
        'Loft window', 'Glazing wall', 'Stair · LED', 'Hall · empty',
        'Bath · glass shower', 'Stair · drawer', 'Loft door',
        'Living · galley nook', 'Door knob detail', 'Worktop close',
        'Living · loft above', 'Galley · detail', 'Bath · wide',
        'Bath · industrial', 'Galley · black sink', 'Door view',
        'Living · low couch', 'Galley · marble', 'Door · glass', 'Hall · galley',
        'Pentagon window · in', 'Stair · oak',
        'Living · grey · caravan view', 'Bath · vessel sink',
        'Bath · counter', 'Bath · WC',
        'Stair · drawers',
      ],
      story: 'A garden cabin that never asks for planning permission. Built around a 750 kg trailer, it ships door-to-door anywhere in the UK or EU. Cedar T&G outside, full electrical and a Velux roof window — small enough to be a desk, big enough to be a guest room.',
    },
    {
      id: 'th-lodge',
      name: 'Family Lodge',
      sub: 'Permanent foundation · two-bedroom · 4–6 berth',
      length: '12.0 m',
      width: '7.5 m',
      height: '5.20 m',
      sleeps: '4–6',
      area: '78 m²',
      weight: 'Slab-mounted',
      priceGBP: 78000,
      priceEUR: 91200,
      frame: '140 mm LGSF · twin-gable',
      insulation: '130 mm Rockwool walls · 200 mm roof',
      cladding: 'Composite siding · stone-clad base',
      roof: 'Asymmetric metal tile',
      hero: i(7),
      images: [
        i(7), i(115), i(9), i(10), i(108), i(109), i(110), i(111), i(112), i(113), i(121),
        i(3), i(4), i(5), i(6), i(8),
        i(75), i(79), i(82), i(83), i(84), i(85), i(86), i(87), i(89), i(90),
        i(92), i(93), i(94), i(95), i(96), i(97), i(98), i(101), i(105), i(106), i(107),
      ],
      thumbCaptions: [
        '¾ Exterior · stone base', 'Frame on plot', 'BIM · structure', 'BIM · roof',
        'Frame · long view', 'Frame · plan stage', 'Frame · perspective',
        'Frame · gable raised', 'Frame · trusses', 'Frame · close',
        'Frame · sky',
        'Frame · two-storey', 'Frame · hilltop', 'Frame · twin-gable', 'Interior · drywall', 'Truss · IGSF',
        'Galley · grand', 'Galley · TV nook', 'Hall · dark', 'Door view',
        'Bath · washing', 'Lounge · empty',
        'Door · oak', 'Galley · red', 'Worktop · stone',
        'Galley · window',
        'Worktop · close', 'Living · pentagon', 'Galley · alt', 'Empty long',
        'Galley · close', 'Bath · galley', 'Galley · top-down',
        'Bath · luxe', 'Bath · close', 'Bath · vanity', 'Hall · mid',
      ],
      story: 'A permanent home built on a concrete slab to the same atelier specification as our towable cabins. Twin-gable, two-bedroom, with a south-facing veranda and stone-clad apron at the base. Engineered for snow loads up to 1.5 kN/m² and seismic zones to T0.4g.',
    },
    {
      id: 'th-callisto',
      name: 'Callisto 10',
      sub: 'Modern lodge · 10 m towable · two-berth + loft',
      length: '10.0 m',
      width: '2.55 m',
      height: '4.00 m',
      sleeps: '2 + loft',
      area: '32 m²',
      weight: '5,400 kg',
      priceGBP: 49500,
      priceEUR: 57900,
      frame: '140 mm LGSF · welded chassis · braked',
      insulation: '130 mm Rockwool · 100 mm roof',
      cladding: 'Composite wood + standing-seam steel',
      roof: 'Standing-seam steel · charcoal',
      hero: ca(1),
      images: Array.from({length: 41}, (_, n) => ca(n + 1)),
      thumbCaptions: Array.from({length: 41}, (_, n) => `Callisto · plate ${n + 1}`),
      pdf: 'public/media/callisto-model.pdf',
      pdfLabel: 'Callisto 10 spec book — 41-page PDF',
      story: 'A 10-metre towable lodge built around the same 140 mm LGSF wall as our larger family lodges. Standing-seam steel and composite wood-look siding outside; pink-blush kitchen cabinets, a king-size sleeping loft and a full shower room inside. The 41-page spec book below shows every angle of two completed Callistos — one in factory fit-out, one fully styled.',
    },
    {
      id: 'th-pavilion',
      name: 'Atelier Pavilion',
      sub: 'Custom commission · villa scale · from drawings',
      length: 'Bespoke',
      width: 'Bespoke',
      height: 'Bespoke',
      sleeps: 'Custom',
      area: '60–200 m²',
      weight: 'Slab-mounted',
      priceGBP: 140000,
      priceEUR: 163800,
      frame: 'LGSF · engineered to brief',
      insulation: 'Rockwool · U=0.20 W/m²K',
      cladding: 'Specified to your architect',
      roof: 'Flat or low-pitch standing-seam',
      hero: i(117),
      images: [i(117), i(118), i(119), i(120), i(116), i(114), i(11), i(12), i(13), i(99)],
      thumbCaptions: [
        'Pool pavilion', 'Garden side', 'Step approach', 'Dusk view',
        'A-frame retreat', 'Atelier · Türkoğlu', 'Drawing · roof',
        'Drawing · plan',  'Drawing · section', 'Stockyard',
      ],
      story: 'When clients arrive with their own drawings, we engineer the LGSF frame, prefabricate every panel, and ship a numbered kit. The pool pavilion shown here is a 96 m² commission for a private estate; the A-frame retreat is a 28 m² guesthouse with a covered deck. Lead times match our standard models.',
    },
  ],

  // Frame Systems — eight LGSF / insulation / chassis / finish products,
  // each tied to its real photographs.
  steel: [
    {
      id: 'lgsf-c140',
      name: 'LGSF C-Section · 140 mm',
      spec: 'C140 × 50 × 1.5',
      grade: 'S350GD+Z275 / EN 10346',
      yield: '350 N/mm²',
      tensile: '420 N/mm²',
      length: '6.0 / 12.0 m',
      weight: '3.6 kg/m',
      priceGBP: 14,
      priceEUR: 16,
      unit: 'per metre',
      stock: 'In stock · 18 t',
      hero: i(37),
      images: [i(37), i(115), i(8), i(108), i(109), i(110), i(111), i(112), i(121), i(3), i(4), i(5), i(6), i(113)],
      story: 'Our standard wall stud. Roll-formed in our atelier from S350GD+Z275 strip, hot-dip galvanised in the same coil. The 1.5 mm web is the load-bearing minimum we will sell — no light-duty 1.0 mm shortcuts.',
    },
    {
      id: 'lgsf-truss',
      name: 'LGSF Roof Truss',
      spec: 'Engineered span 4–9 m',
      grade: 'S350GD+Z275',
      yield: '350 N/mm²',
      tensile: '420 N/mm²',
      length: 'Cut to project',
      weight: 'Spec-dependent',
      priceGBP: 38,
      priceEUR: 44,
      unit: 'per m² of roof',
      stock: 'Roll-to-order · 2 wk',
      hero: i(8),
      images: [i(8), i(9), i(10), i(115)],
      story: 'Pre-fabricated trusses delivered numbered to plan. Each truss is engineered against EN 1993-1-3, snow-loaded for the destination postcode, and ships with the bolt schedule and welder’s number.',
    },
    {
      id: 'chassis-tandem',
      name: 'Tandem Trailer Chassis',
      spec: '750 kg / 3,500 kg axle · braked',
      grade: 'EN 1090-1 EXC2',
      yield: 'Welded S275JR',
      tensile: 'Type-approved',
      length: '5.5 / 7.5 / 9.5 m',
      weight: '780–1,100 kg',
      priceGBP: 4200,
      priceEUR: 4900,
      unit: 'per chassis',
      stock: 'In stock · 12 sets',
      hero: i(37),
      images: [i(37), i(104), i(100), i(102), i(103), i(54)],
      story: 'Our towable models ride on a tandem-axle, welded chassis with electric-over-hydraulic brakes and integrated levelling jacks. Type-approved for European road use; UK NTTA registration handled in-house.',
    },
    {
      id: 'rockwool-130',
      name: 'Rockwool Wall Pack · 130 mm',
      spec: 'Density 50 kg/m³ · λ 0.035 W/mK',
      grade: 'EN 13162 / A1 fire',
      yield: '—',
      tensile: '—',
      length: '1200 × 600',
      weight: '6.5 kg/m²',
      priceGBP: 22,
      priceEUR: 26,
      unit: 'per m²',
      stock: 'In stock · 4,200 m²',
      hero: i(2),
      images: [i(2), i(1), i(99)],
      story: 'The 130 mm slab inside every wall we ship. Non-combustible (EN 13501-1 class A1), λ = 0.035 W/mK, friction-fitted between the steel studs without compression. Floor pack is 80 mm of the same.',
    },
    {
      id: 'metal-tile-roof',
      name: 'Metal Tile Roof Sheet',
      spec: 'Profiled · 0.5 mm · pre-painted',
      grade: 'S280GD+AZ150',
      yield: '280 N/mm²',
      tensile: '360 N/mm²',
      length: 'Cut to length',
      weight: '4.6 kg/m²',
      priceGBP: 18,
      priceEUR: 21,
      unit: 'per m²',
      stock: 'In stock · 2,800 m²',
      hero: i(26),
      images: [i(26), i(41), i(63), i(64), i(40), i(78)],
      story: 'A pressed-tile profile in PVDF-coated S280GD strip. Standard charcoal, RAL 9005 matt, or custom on roll-to-order. Mounted on 11 mm OSB over a vapour-permeable membrane.',
    },
    {
      id: 'cladding-composite',
      name: 'Composite Wood-Look Cladding',
      spec: '170 × 22 mm · T&G',
      grade: 'WPC · UV-stable',
      yield: '—',
      tensile: '—',
      length: '4.0 / 6.0 m',
      weight: '2.1 kg/m',
      priceGBP: 38,
      priceEUR: 44,
      unit: 'per m²',
      stock: 'In stock · 1,650 m²',
      hero: i(53),
      images: [i(53), i(100), i(104), i(54), i(78), i(102)],
      story: 'A wood-polymer composite that doesn’t need re-staining and won’t check or split. We use it on every Voyager and Vortex. UV-stable, BBA-tested, available in five tones.',
    },
    {
      id: 'aluminum-cladding',
      name: 'Aluminium Foil Cladding System',
      spec: '0.6 mm sheet · clip-fix',
      grade: 'EN AW-3003',
      yield: '—',
      tensile: '—',
      length: 'To 6.0 m',
      weight: '1.7 kg/m²',
      priceGBP: 46,
      priceEUR: 54,
      unit: 'per m²',
      stock: 'In stock · 980 m²',
      hero: i(1),
      images: [i(1), i(2)],
      story: 'The outer skin behind our decorative-plaster finish. Aluminium foil over a vapour-control membrane, fixed with stainless clips so the thermal bridge is broken at every contact.',
    },
    {
      id: 'bim-package',
      name: 'BIM Structural Package',
      spec: 'Tekla / Revit · per drawing',
      grade: 'EN 1993-1-3',
      yield: '—',
      tensile: '—',
      length: 'Project-scoped',
      weight: '—',
      priceGBP: 3200,
      priceEUR: 3750,
      unit: 'per project',
      stock: 'On request · 5 day turnaround',
      hero: i(9),
      images: [i(9), i(10), i(11), i(12), i(13), i(114)],
      story: 'For architects who want the steel modelled before they spec the cladding. We deliver a Tekla or Revit model, snow- and seismic-loaded for the destination, with calc sheets and weld schedule. The Keele Northbound (Matrix Construction) drawings shown here are part of a 2022 commission.',
    },
  ],

  reviews: [
    {
      stars: 5,
      text: 'The Serenity arrived on a low-loader, the levelling jacks dropped, and we slept in it the same night. The wall build-up is exactly what they said — you can hear the rockwool the moment you close the door.',
      name: 'M. Yıldız',
      meta: 'Serenity · Muğla',
    },
    {
      stars: 5,
      text: 'Three Voyagers delivered to a campsite in Kent. Zero snags. The standing-seam roof shrugged off a January storm we had to evacuate the rest of the site for.',
      name: 'Coastal Retreats Ltd',
      meta: 'Trade · 3 × Voyager · Kent',
    },
    {
      stars: 5,
      text: 'They engineered the LGSF frame for our 240 m² project in Staffordshire to a tighter tolerance than our local supplier could quote. Drawings, calcs and welder’s number on every truss.',
      name: 'Matrix Construction',
      meta: 'Trade · Keele Northbound',
    },
    {
      stars: 5,
      text: 'The Aurora A-frame is the third tiny house we have bought and the first one that didn’t need a snag list. Cedar cladding, brass kitchen pulls, the lot. Towed it 2,400 km to a forest plot in Bavaria with no complaint.',
      name: 'P. Roth',
      meta: 'Aurora · Bavaria',
    },
  ],

  certs: ['EN 1090-1 EXC2', 'EN 1993-1-3 LGSF', 'EN 13162 Rockwool', 'CE / UKCA', 'ISO 9001', 'EN 10346 Galv'],
};
