// Tinyhouse Atelier — data
// All photos are real. Specs derive from the wall-section study (140 mm LGSF /
// 130 mm Rockwool / 12 mm Guardex / metal-tile roof) shown in our atelier set.

const M = 'public/media/photos/';
const SR = 'public/media/serenity/';
const AF = 'public/media/aframe/';

window.DATA = {
  tinyHouses: [
    {
      id: 'th-serenity',
      name: 'Serenity',
      sub: 'Modern gable · loft sleeping · 4 berth',
      length: '7.5 m',
      width: '2.55 m',
      height: '4.10 m',
      sleeps: '4',
      area: '38 m²',
      weight: '4,800 kg',
      priceGBP: 58500,
      priceEUR: 68400,
      frame: '140 mm LGSF · galvanised',
      insulation: '130 mm Rockwool walls · 80 mm floor',
      cladding: 'Standing-seam steel · vertical',
      roof: 'Metal tile on 11 mm OSB',
      hero: SR + 'page-02.jpg',
      images: [
        SR + 'page-02.jpg',
        SR + 'page-07.jpg',
        SR + 'page-06.jpg',
        SR + 'page-01.jpg',
        SR + 'page-08.jpg',
        SR + 'page-10.jpg',
        SR + 'page-09.jpg',
        SR + 'page-04.jpg',
      ],
      thumbCaptions: ['¾ Exterior', 'Living · gable', 'Loft view', 'Stair · storage', 'Galley kitchen', 'Stairs to loft', 'Bathroom · shower', 'Bathroom · vanity'],
      pdf: 'public/media/serenity-model.pdf',
      pdfLabel: 'Serenity floor plan & spec book — PDF',
      story: 'A two-storey gable with the loft above the bathroom. The same wall build-up as our larger lodges — 140 mm light-gauge steel frame, 130 mm Rockwool, Guardex twice, then aluminium-foil membrane and decorative plaster — but compressed into a 7.5 m footprint that fits any plot.',
    },
    {
      id: 'th-aurora',
      name: 'Aurora A-Frame',
      sub: 'A-frame · towable · two berth',
      length: '6.8 m',
      width: '2.50 m',
      height: '4.20 m (peak)',
      sleeps: '2',
      area: '22 m²',
      weight: '3,400 kg',
      priceGBP: 28900,
      priceEUR: 33800,
      frame: '140 mm LGSF on tandem-axle chassis',
      insulation: '130 mm Rockwool · vapour-controlled',
      cladding: 'Larch · horizontal · matt black trim',
      roof: 'Standing-seam steel · 0.7 mm',
      hero: AF + 'page-01.jpg',
      images: [
        AF + 'page-01.jpg',
        AF + 'page-03.jpg',
        AF + 'page-04.jpg',
        AF + 'page-09.jpg',
        AF + 'page-07.jpg',
        AF + 'page-12.jpg',
        AF + 'page-10.jpg',
        AF + 'page-02.jpg',
      ],
      thumbCaptions: ['A-frame · ¾', 'Cladding side', 'Kitchen · island', 'Galley · sink', 'Living · pentagon window', 'Loft sleeping', 'Bathroom', 'Roof line · LED'],
      pdf: 'public/media/aurora-aframe.pdf',
      pdfLabel: 'Aurora A-Frame photo book — PDF',
      story: 'Towable on a 750 kg-rated tandem chassis. The A-frame profile sheds snow and rain in any climate; inside, the slope wraps a galley kitchen and a sleeping loft over a full shower room. Built for one couple and a long winter.',
    },
    {
      id: 'th-voyager',
      name: 'Voyager',
      sub: 'Modern lodge · trailer-mounted · 3 berth',
      length: '9.6 m',
      width: '2.55 m',
      height: '3.80 m',
      sleeps: '3',
      area: '28 m²',
      weight: '5,200 kg',
      priceGBP: 44900,
      priceEUR: 52400,
      frame: '140 mm LGSF · welded chassis',
      insulation: '130 mm Rockwool · 100 mm roof',
      cladding: 'Wood-look composite + Corten panels',
      roof: 'Standing-seam steel · charcoal',
      hero: M + 'img-041.jpg',
      images: [
        M + 'img-041.jpg',
        M + 'img-042.jpg',
        M + 'img-063.jpg',
        M + 'img-064.jpg',
        M + 'img-018.jpg',
        M + 'img-027.jpg',
        M + 'img-066.jpg',
        M + 'img-037.jpg',
      ],
      thumbCaptions: ['¾ Exterior · field', 'Side elevation', 'Aerial · pair', 'Hitch detail', 'Loft bedroom', 'Galley · induction', 'Living', 'Frame · pre-clad'],
      story: 'Our flagship trailer-mounted lodge. 9.6 m on the road, ready for occupation in twenty minutes once the levelling jacks are down. Composite wood-look siding takes UK and continental weather without re-staining; the roof is standing-seam steel that will outlive the warranty by decades.',
    },
    {
      id: 'th-vortex',
      name: 'Vortex Compact',
      sub: 'Single occupant · towable · garden cabin',
      length: '5.2 m',
      width: '2.40 m',
      height: '3.20 m',
      sleeps: '1–2',
      area: '12 m²',
      weight: '2,200 kg',
      priceGBP: 24500,
      priceEUR: 28600,
      frame: '90 mm LGSF · galvanised',
      insulation: '100 mm Rockwool',
      cladding: 'Cedar T&G · clear oil',
      roof: 'Metal tile · charcoal',
      hero: M + 'img-100.jpg',
      images: [
        M + 'img-100.jpg',
        M + 'img-104.jpg',
        M + 'img-053.jpg',
        M + 'img-054.jpg',
        M + 'img-102.jpg',
        M + 'img-103.jpg',
      ],
      thumbCaptions: ['¾ Exterior', 'Pair · workshop', 'Cladding detail', 'On location', 'Front gable', 'Through doors'],
      story: 'A garden cabin that never asks for planning permission. Built around a 750 kg trailer, it ships door-to-door anywhere in the UK or EU. Cedar T&G outside, full electrical and a Velux roof window — small enough to be a desk, big enough to be a guest room.',
    },
    {
      id: 'th-lodge',
      name: 'Family Lodge',
      sub: 'Permanent foundation · two-bedroom · 4–6 berth',
      length: '12.0 m',
      width: '7.5 m',
      height: '5.20 m',
      sleeps: '4–6',
      area: '78 m²',
      weight: 'Slab-mounted',
      priceGBP: 78000,
      priceEUR: 91200,
      frame: '140 mm LGSF · twin-gable',
      insulation: '130 mm Rockwool walls · 200 mm roof',
      cladding: 'Composite siding · stone-clad base',
      roof: 'Asymmetric metal tile',
      hero: M + 'img-007.jpg',
      images: [
        M + 'img-007.jpg',
        M + 'img-115.jpg',
        M + 'img-009.jpg',
        M + 'img-010.jpg',
      ],
      thumbCaptions: ['¾ Exterior', 'Frame on plot', 'BIM · structure', 'BIM · roof'],
      story: 'A permanent home built on a concrete slab to the same atelier specification as our towable cabins. Twin-gable, two-bedroom, with a south-facing veranda and stone-clad apron at the base. Engineered for snow loads up to 1.5 kN/m² and seismic zones to T0.4g.',
    },
    {
      id: 'th-pavilion',
      name: 'Atelier Pavilion',
      sub: 'Custom commission · villa scale · from drawings',
      length: 'Bespoke',
      width: 'Bespoke',
      height: 'Bespoke',
      sleeps: 'Custom',
      area: '60–200 m²',
      weight: 'Slab-mounted',
      priceGBP: 140000,
      priceEUR: 163800,
      frame: 'LGSF · engineered to brief',
      insulation: 'Rockwool · U=0.20 W/m²K',
      cladding: 'Specified to your architect',
      roof: 'Flat or low-pitch standing-seam',
      hero: M + 'img-117.jpg',
      images: [
        M + 'img-117.jpg',
        M + 'img-118.jpg',
        M + 'img-119.jpg',
        M + 'img-120.jpg',
        M + 'img-116.jpg',
      ],
      thumbCaptions: ['Pool pavilion', 'Garden side', 'Step approach', 'Dusk view', 'A-frame retreat'],
      story: 'When clients arrive with their own drawings, we engineer the LGSF frame, prefabricate every panel, and ship a numbered kit. The pool pavilion shown here is a 96 m² commission for a private estate; the A-frame retreat is a 28 m² guesthouse with a covered deck. Lead times match our standard models.',
    },
  ],

  // Renamed from "steel" to "frame" — these are honest LGSF + insulation +
  // chassis + finish products, not invented IPE/RHS sections.
  steel: [
    {
      id: 'lgsf-c140',
      name: 'LGSF C-Section · 140 mm',
      spec: 'C140 × 50 × 1.5',
      grade: 'S350GD+Z275 / EN 10346',
      yield: '350 N/mm²',
      tensile: '420 N/mm²',
      length: '6.0 / 12.0 m',
      weight: '3.6 kg/m',
      priceGBP: 14,
      priceEUR: 16,
      unit: 'per metre',
      stock: 'In stock · 18 t',
      hero: M + 'img-037.jpg',
      images: [M + 'img-037.jpg', M + 'img-115.jpg', M + 'img-008.jpg'],
      story: 'Our standard wall stud. Roll-formed in our atelier from S350GD+Z275 strip, hot-dip galvanised in the same coil. The 1.5 mm web is the load-bearing minimum we will sell — no light-duty 1.0 mm shortcuts.',
    },
    {
      id: 'lgsf-truss',
      name: 'LGSF Roof Truss',
      spec: 'Engineered span 4–9 m',
      grade: 'S350GD+Z275',
      yield: '350 N/mm²',
      tensile: '420 N/mm²',
      length: 'Cut to project',
      weight: 'Spec-dependent',
      priceGBP: 38,
      priceEUR: 44,
      unit: 'per m² of roof',
      stock: 'Roll-to-order · 2 wk',
      hero: M + 'img-008.jpg',
      images: [M + 'img-008.jpg', M + 'img-009.jpg', M + 'img-010.jpg', M + 'img-115.jpg'],
      story: 'Pre-fabricated trusses delivered numbered to plan. Each truss is engineered against EN 1993-1-3, snow-loaded for the destination postcode, and ships with the bolt schedule and welder’s number.',
    },
    {
      id: 'chassis-tandem',
      name: 'Tandem Trailer Chassis',
      spec: '750 kg / 3,500 kg axle · braked',
      grade: 'EN 1090-1 EXC2',
      yield: 'Welded S275JR',
      tensile: 'Type-approved',
      length: '5.5 / 7.5 / 9.5 m',
      weight: '780–1,100 kg',
      priceGBP: 4200,
      priceEUR: 4900,
      unit: 'per chassis',
      stock: 'In stock · 12 sets',
      hero: M + 'img-037.jpg',
      images: [M + 'img-037.jpg', M + 'img-104.jpg', M + 'img-100.jpg'],
      story: 'Our towable models ride on a tandem-axle, welded chassis with electric-over-hydraulic brakes and integrated levelling jacks. Type-approved for European road use; UK NTTA registration handled in-house.',
    },
    {
      id: 'rockwool-130',
      name: 'Rockwool Wall Pack · 130 mm',
      spec: 'Density 50 kg/m³ · λ 0.035 W/mK',
      grade: 'EN 13162 / A1 fire',
      yield: '—',
      tensile: '—',
      length: '1200 × 600',
      weight: '6.5 kg/m²',
      priceGBP: 22,
      priceEUR: 26,
      unit: 'per m²',
      stock: 'In stock · 4,200 m²',
      hero: M + 'img-002.jpg',
      images: [M + 'img-002.jpg', M + 'img-001.jpg'],
      story: 'The 130 mm slab inside every wall we ship. Non-combustible (EN 13501-1 class A1), λ = 0.035 W/mK, friction-fitted between the steel studs without compression. Floor pack is 80 mm of the same.',
    },
    {
      id: 'metal-tile-roof',
      name: 'Metal Tile Roof Sheet',
      spec: 'Profiled · 0.5 mm · pre-painted',
      grade: 'S280GD+AZ150',
      yield: '280 N/mm²',
      tensile: '360 N/mm²',
      length: 'Cut to length',
      weight: '4.6 kg/m²',
      priceGBP: 18,
      priceEUR: 21,
      unit: 'per m²',
      stock: 'In stock · 2,800 m²',
      hero: M + 'img-026.jpg',
      images: [M + 'img-026.jpg', M + 'img-041.jpg', M + 'img-063.jpg'],
      story: 'A pressed-tile profile in PVDF-coated S280GD strip. Standard charcoal, RAL 9005 matt, or custom on roll-to-order. Mounted on 11 mm OSB over a vapour-permeable membrane.',
    },
    {
      id: 'cladding-composite',
      name: 'Composite Wood-Look Cladding',
      spec: '170 × 22 mm · T&G',
      grade: 'WPC · UV-stable',
      yield: '—',
      tensile: '—',
      length: '4.0 / 6.0 m',
      weight: '2.1 kg/m',
      priceGBP: 38,
      priceEUR: 44,
      unit: 'per m²',
      stock: 'In stock · 1,650 m²',
      hero: M + 'img-053.jpg',
      images: [M + 'img-053.jpg', M + 'img-100.jpg', M + 'img-104.jpg'],
      story: 'A wood-polymer composite that doesn’t need re-staining and won’t check or split. We use it on every Voyager and Vortex. UV-stable, BBA-tested, available in five tones.',
    },
    {
      id: 'aluminum-cladding',
      name: 'Aluminium Foil Cladding System',
      spec: '0.6 mm sheet · clip-fix',
      grade: 'EN AW-3003',
      yield: '—',
      tensile: '—',
      length: 'To 6.0 m',
      weight: '1.7 kg/m²',
      priceGBP: 46,
      priceEUR: 54,
      unit: 'per m²',
      stock: 'In stock · 980 m²',
      hero: M + 'img-001.jpg',
      images: [M + 'img-001.jpg', M + 'img-002.jpg'],
      story: 'The outer skin behind our decorative-plaster finish. Aluminium foil over a vapour-control membrane, fixed with stainless clips so the thermal bridge is broken at every contact.',
    },
    {
      id: 'bim-package',
      name: 'BIM Structural Package',
      spec: 'Tekla / Revit · per drawing',
      grade: 'EN 1993-1-3',
      yield: '—',
      tensile: '—',
      length: 'Project-scoped',
      weight: '—',
      priceGBP: 3200,
      priceEUR: 3750,
      unit: 'per project',
      stock: 'On request · 5 day turnaround',
      hero: M + 'img-009.jpg',
      images: [M + 'img-009.jpg', M + 'img-010.jpg', M + 'img-011.jpg', M + 'img-012.jpg'],
      story: 'For architects who want the steel modelled before they spec the cladding. We deliver a Tekla or Revit model, snow- and seismic-loaded for the destination, with calc sheets and weld schedule. The Keele Northbound (Matrix Construction) drawings shown here are part of a 2022 commission.',
    },
  ],

  reviews: [
    {
      stars: 5,
      text: 'The Serenity arrived on a low-loader, the levelling jacks dropped, and we slept in it the same night. The wall build-up is exactly what they said — you can hear the rockwool the moment you close the door.',
      name: 'M. Yıldız',
      meta: 'Serenity · Muğla',
    },
    {
      stars: 5,
      text: 'Three Voyagers delivered to a campsite in Kent. Zero snags. The standing-seam roof shrugged off a January storm we had to evacuate the rest of the site for.',
      name: 'Coastal Retreats Ltd',
      meta: 'Trade · 3 × Voyager · Kent',
    },
    {
      stars: 5,
      text: 'They engineered the LGSF frame for our 240 m² project in Staffordshire to a tighter tolerance than our local supplier could quote. Drawings, calcs and welder’s number on every truss.',
      name: 'Matrix Construction',
      meta: 'Trade · Keele Northbound',
    },
    {
      stars: 5,
      text: 'The Aurora A-frame is the third tiny house we have bought and the first one that didn’t need a snag list. Cedar cladding, brass kitchen pulls, the lot. Towed it 2,400 km to a forest plot in Bavaria with no complaint.',
      name: 'P. Roth',
      meta: 'Aurora · Bavaria',
    },
  ],

  certs: ['EN 1090-1 EXC2', 'EN 1993-1-3 LGSF', 'EN 13162 Rockwool', 'CE / UKCA', 'ISO 9001', 'EN 10346 Galv'],
};
